### ISSUE TITLE
Don't you have to add self.previousHash?

### ISSUE THREAD

**Issue by ahanikel** [daxeel/blockshell#2]
I'm sorry in advance if I'm wrong, but don't you also need to add `self.previousHash` to `hashData` at 
https://github.com/daxeel/blockshell/blob/6aa5eec11aa107f754e2abdc86e79c4249578c2c/blockchain/chain.py#L19 ?

**Comment by daxeel** [comment]
@ahanikel Thanks for your report. PreviousHash must be in hash calculation. You are welcome to submit PR with this edit.

**Comment by ahanikel** [comment]
Ok, done. Thanks a lot for your work, I'm sure many people (including myself) benefit from it!
