### ISSUE TITLE
Can I store the result?

### ISSUE THREAD

**Issue by sttyru** [daxeel/blockshell#9]
Hello!

Thank you for this software! It's impressive :)
Can I store the result to transfer between hosts and usage for something else?

Thank you.

**Comment by daxeel** [comment]
Ya as of now in version 1, all the blockchain data is stored in chain.txt file in the working directory. In next release, Blockshell will support distributed data.
For your question, yes you have to modify **/blockchain/chain.py** to connect to your server and you directly pass blockchain data to your remote server.
All blockchain data is stored in **chain** variable of **chain.py**

**Comment by sttyru** [comment]
Thank you!

Maybe I miss an edge of technology, but I can't to reuse the chain.txt. Maybe I need to run the application with some special switches?
